### ISSUE TITLE
SeekerMissile throws exception when no targets in range

### ISSUE THREAD

**Issue by Delraich** [EntelectChallenge/2017-Battleships#48] opened 2017-06-17 12:39 UTC
When the seekermissle has no targets in range, an exception is thrown, causing the shot to do nothing.

The following code fixes the problem, but might not be so very elegant.
`Point cellToHit;
try
{
  var cellInRange = occupiedCells.Select(x => new
  {
    distance = Math.Sqrt(Math.Pow((x.X - _centerPoint.X), 2) + Math.Pow(x.Y - _centerPoint.Y, 2)),
                            cell = x
                        }).OrderBy(x => x.distance).First(x => x.distance <= 2);
                        cellToHit = new Point(cellInRange.cell.X, cellInRange.cell.Y);
                        gameMap.Shoot(player.PlayerType, new List<Point> { cellToHit }, WeaponType.SeekerMissle);
}
catch (InvalidOperationException ioe)
{
  cellToHit = new Point(_centerPoint.X, _centerPoint.Y);
  gameMap.Shoot(player.PlayerType, new List<Point> { cellToHit }, WeaponType.SeekerMissle);
}`

**Comment by JWorthe** [comment] 2017-06-17 14:14
I don't have an example bot up using this shot to test this or set up a pull request, but I think the fix can be simpler than that.

You just need to take the `First` in `}).OrderBy(x => x.distance).First(x => x.distance <= 2);` and replace it with `FirstOrDefault` (which returns null for empty lists).

So the new line becomes `}).OrderBy(x => x.distance).FirstOrDefault(x => x.distance <= 2);`

I see they already handle a null on the following line, so that's probably what was intended?

**Comment by Delraich** [comment] 2017-06-17 14:48
I actually had the issue that a FirstOrDefault returned a Point(0,0) instead of the expected null, which is why I steered away from it for this release. But this was a quick and dirty fix so you might be right. I'll give it a shot a bit later.

**Comment by Delraich** [comment] 2017-06-17 15:40
It appears that does indeed work. using FirsOrDefault instead of Just First

**Comment by Delraich** [comment] 2017-06-17 18:17
Submitted this change into my pull request that should contain all fixes for the rest of the shots aswell.

**Comment by JWorthe** [comment] 2017-06-18 06:22
Nice one Delraich! Thanks for putting in the work :D

**Comment by EntelectChallenge** [comment] 2017-06-18 09:54
Hey guys thanks for the fix, it has been merged 👍

**Closed as completed by EntelectChallenge** 2017-06-18 09:54 UTC
